language: bash 
services:
  - docker

before_install:
- docker build -t thrust github.com/thrustjs/thrust-docker

script: docker run --rm -v $(pwd):/app -w /app/test thrustjs/thrust-docker /bin/sh -c "thrust install && thrust test.router.js"

deploy:
  provider: releases
  api_key: $githubToken
  skip_cleanup: true
  on:
    tags: true
